// Initial database content - converted from mockData.ts
module.exports = {
  categories: [
    {
      id: '1',
      name: {
        uz: 'Qadoqlash sanoati',
        ru: 'Упаковочная промышленность',
        en: 'Packaging Industry',
      },
      slug: 'packaging',
      image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400',
      productCount: 44,
    },
    {
      id: '2',
      name: {
        uz: 'Metalga ishlov berish',
        ru: 'Металлообработка',
        en: 'Metal Processing',
      },
      slug: 'metal',
      image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
      productCount: 28,
    },
    {
      id: '3',
      name: {
        uz: 'Oziq-ovqat sanoati',
        ru: 'Пищевая промышленность',
        en: 'Food Industry',
      },
      slug: 'food',
      image: 'https://images.unsplash.com/photo-1584269600519-112d071b35e6?w=400',
      productCount: 56,
    },
    {
      id: '4',
      name: {
        uz: 'Muzlatgichlar',
        ru: 'Холодильное оборудование',
        en: 'Refrigeration',
      },
      slug: 'refrigeration',
      image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400',
      productCount: 32,
    },
    {
      id: '5',
      name: {
        uz: 'Non mahsulotlari',
        ru: 'Хлебопекарное оборудование',
        en: 'Bakery Equipment',
      },
      slug: 'bakery',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
      productCount: 24,
    },
    {
      id: '6',
      name: {
        uz: 'Qurilish sanoati',
        ru: 'Строительная промышленность',
        en: 'Construction Industry',
      },
      slug: 'construction',
      image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
      productCount: 38,
    },
    {
      id: '7',
      name: {
        uz: 'Yog\'och qayta ishlash',
        ru: 'Деревообработка',
        en: 'Woodworking',
      },
      slug: 'woodworking',
      image: 'https://images.unsplash.com/photo-1416339306562-f3d12fefd36f?w=400',
      productCount: 19,
    },
    {
      id: '8',
      name: {
        uz: 'Qishloq xo\'jaligi',
        ru: 'Сельскохозяйственное оборудование',
        en: 'Agricultural Equipment',
      },
      slug: 'agriculture',
      image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400',
      productCount: 42,
    },
  ],

  products: [
    {
      id: '1',
      name: {
        uz: 'Avtomatik vertikal qadoqlash uskunalari',
        ru: 'Автоматическое вертикальное упаковочное оборудование',
        en: 'Automatic Vertical Packaging Machine',
      },
      description: {
        uz: 'Yuqori sifatli avtomatik qadoqlash uskunasi. Ishlab chiqarish quvvati: 60-80 dona/minut.',
        ru: 'Высококачественное автоматическое упаковочное оборудование. Производительность: 60-80 шт/мин.',
        en: 'High-quality automatic packaging equipment. Production capacity: 60-80 pcs/min.',
      },
      price: 12500000,
      categoryId: '1',
      images: [
        'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600',
        'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600',
      ],
      inStock: true,
      availabilityType: 'in_stock',
      createdAt: '2024-01-15',
    },
    {
      id: '2',
      name: {
        uz: 'Vakuumli qadoqlash uskunalari',
        ru: 'Вакуумное упаковочное оборудование',
        en: 'Vacuum Packaging Machine',
      },
      description: {
        uz: 'Professional vakuumli qadoqlash uskunasi. Oziq-ovqat mahsulotlari uchun ideal.',
        ru: 'Профессиональное вакуумное упаковочное оборудование. Идеально для пищевых продуктов.',
        en: 'Professional vacuum packaging equipment. Ideal for food products.',
      },
      price: 8500000,
      categoryId: '1',
      images: ['https://images.unsplash.com/photo-1584269600519-112d071b35e6?w=600'],
      inStock: true,
      availabilityType: 'in_stock',
      createdAt: '2024-01-20',
    },
    {
      id: '3',
      name: {
        uz: 'CNC frezalash uskunalari',
        ru: 'CNC фрезерный станок',
        en: 'CNC Milling Machine',
      },
      description: {
        uz: 'Aniq CNC frezalash uskunasi. Metalga ishlov berish uchun.',
        ru: 'Точный CNC фрезерный станок. Для обработки металла.',
        en: 'Precision CNC milling machine. For metal processing.',
      },
      price: 45000000,
      categoryId: '2',
      images: ['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600'],
      inStock: true,
      availabilityType: 'in_stock',
      createdAt: '2024-02-01',
    },
    {
      id: '4',
      name: {
        uz: 'Lazer kesish uskunalari',
        ru: 'Лазерный резак',
        en: 'Laser Cutting Machine',
      },
      description: {
        uz: 'Yuqori quvvatli lazer kesish uskunasi. Aniq va tez ishlov berish.',
        ru: 'Высокомощный лазерный резак. Точная и быстрая обработка.',
        en: 'High-power laser cutting machine. Precise and fast processing.',
      },
      price: 78000000,
      categoryId: '2',
      images: ['https://images.unsplash.com/photo-1615811361269-ffc8411d51b8?w=600'],
      inStock: true,
      availabilityType: 'in_stock',
      createdAt: '2024-02-10',
    },
    {
      id: '5',
      name: {
        uz: 'Go\'sht maydalagich',
        ru: 'Мясорубка промышленная',
        en: 'Industrial Meat Grinder',
      },
      description: {
        uz: 'Professional go\'sht maydalagich. Katta hajmda ishlov berish uchun.',
        ru: 'Промышленная мясорубка. Для больших объемов переработки.',
        en: 'Industrial meat grinder. For large volume processing.',
      },
      price: 6500000,
      categoryId: '3',
      images: ['https://images.unsplash.com/photo-1584269600519-112d071b35e6?w=600'],
      inStock: true,
      availabilityType: 'in_stock',
      createdAt: '2024-02-15',
    },
    {
      id: '6',
      name: {
        uz: 'Sut qayta ishlash liniyasi',
        ru: 'Линия переработки молока',
        en: 'Milk Processing Line',
      },
      description: {
        uz: 'To\'liq avtomatik sut qayta ishlash liniyasi.',
        ru: 'Полностью автоматическая линия переработки молока.',
        en: 'Fully automatic milk processing line.',
      },
      price: 125000000,
      categoryId: '3',
      images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600'],
      inStock: true,
      availabilityType: 'in_stock',
      createdAt: '2024-02-20',
    },
    {
      id: '7',
      name: {
        uz: 'Sanoat muzlatgichi',
        ru: 'Промышленный холодильник',
        en: 'Industrial Refrigerator',
      },
      description: {
        uz: 'Katta hajmli sanoat muzlatgichi. Restoran va kafelar uchun.',
        ru: 'Большой промышленный холодильник. Для ресторанов и кафе.',
        en: 'Large industrial refrigerator. For restaurants and cafes.',
      },
      price: 15000000,
      categoryId: '4',
      images: ['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600'],
      inStock: true,
      availabilityType: 'in_stock',
      createdAt: '2024-03-01',
    },
    {
      id: '8',
      name: {
        uz: 'Non pechi',
        ru: 'Хлебопекарная печь',
        en: 'Bakery Oven',
      },
      description: {
        uz: 'Professional non pechi. Har xil turdagi non mahsulotlari uchun.',
        ru: 'Профессиональная хлебопекарная печь. Для различных хлебобулочных изделий.',
        en: 'Professional bakery oven. For various bakery products.',
      },
      price: 22000000,
      categoryId: '5',
      images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600'],
      inStock: true,
      availabilityType: 'in_stock',
      createdAt: '2024-03-05',
    },
  ],

  orders: [
    {
      id: '1',
      productId: '1',
      productName: 'Avtomatik vertikal qadoqlash uskunalari',
      customerName: 'Azizbek Karimov',
      customerPhone: '+998 90 123 45 67',
      status: 'pending',
      createdAt: '2024-03-10T10:30:00',
      notes: 'Tez yetkazib berish kerak',
    },
    {
      id: '2',
      productId: '3',
      productName: 'CNC frezalash uskunalari',
      customerName: 'Dilshod Rahimov',
      customerPhone: '+998 91 234 56 78',
      status: 'processing',
      createdAt: '2024-03-09T14:20:00',
    },
    {
      id: '3',
      productId: '5',
      productName: 'Go\'sht maydalagich',
      customerName: 'Nodirbek Aliyev',
      customerPhone: '+998 93 345 67 89',
      status: 'completed',
      createdAt: '2024-03-08T09:15:00',
    },
  ],

  customers: [],

  adminUser: {
    username: 'admin',
    password: 'admin123',
  },

  siteSettings: {
    id: '1',
    siteName: {
      uz: 'Hope Group',
      ru: 'Hope Group',
      en: 'Hope Group',
    },
    logo: '',
    contactPhones: ['+998 33 840 00 05'],
    email: 'oftursunov@gmail.com',
    address: {
      uz: 'Toshkent shahri, Yakkasaroy tumani, Kichik halqa yoʻli, 21A',
      ru: 'г. Ташкент, Яккасарайский район, Кичик халка йули, 21А',
      en: 'Tashkent city, Yakkasaroy district, Kichik halqa yoli, 21A',
    },
    telegramLink: 'https://t.me/hopegroup_uz',
    facebookLink: 'https://facebook.com/hopegroup_uz',
    instagramLink: 'https://instagram.com/hopegroup.uz',
    youtubeLink: 'https://youtube.com/@hopegroup_uz',
    workingHours: {
      uz: 'Dushanba - Shanba: 9:00 - 18:00',
      ru: 'Понедельник - Суббота: 9:00 - 18:00',
      en: 'Monday - Saturday: 9:00 AM - 6:00 PM',
    },
    factoriesLink: 'https://hopegroup.uz',
    protectionPage: {
      uz: 'Buyurtma himoyasi haqida ma\'lumot',
      ru: 'Информация о защите заказа',
      en: 'Order protection information',
    },
    buyerCenterPage: {
      uz: 'Xaridor markazi ma\'lumotlari',
      ru: 'Информация центра покупателей',
      en: 'Buyer center information',
    },
    helpCenterPage: {
      uz: 'Yordam markazi ma\'lumotlari',
      ru: 'Информация справочного центра',
      en: 'Help center information',
    },
    appExtensionPage: {
      uz: 'Ilova va kengaytma ma\'lumotlari',
      ru: 'Информация о приложении и расширении',
      en: 'App and extension information',
    },
    footerDescription: {
      uz: 'Markaziy Osiyodagi eng yirik xalqaro uskunalar savdo markazi.',
      ru: 'Крупнейший международный торговый центр оборудования в Центральной Азии.',
      en: 'The largest international equipment trading center in Central Asia.',
    },
    footerCompanyLinks: [
      {
        label: { uz: 'Kompaniya haqida', ru: 'О компании', en: 'About Company' },
        url: '/about',
      },
      {
        label: { uz: 'Bizning videolar', ru: 'Наши видео', en: 'Our Videos' },
        url: '/videos',
      },
    ],
    copyrightText: {
      uz: 'Copyright © 2006 - {year} Hope Group LLC. Barcha huquqlar himoyalangan',
      ru: 'Copyright © 2006 - {year} Hope Group LLC. Все права защищены',
      en: 'Copyright © 2006 - {year} Hope Group LLC. All rights reserved',
    },
    heroBackgroundImages: [
      'linear-gradient(135deg, #1A1A2E 0%, #16213E 50%, #0F3460 100%)',
      'linear-gradient(135deg, #0F3460 0%, #16213E 50%, #1A1A2E 100%)',
      'linear-gradient(135deg, #16213E 0%, #0F3460 50%, #1A1A2E 100%)',
    ],
    heroCarouselInterval: 5000,
    logoWidth: 120,
    logoHeight: 40,
  },
};
